services:
  - type: web
    name: czsu-multi-agent-text-to-sql
    runtime: python
    buildCommand: curl -LsSf https://astral.sh/uv/install.sh | sh && uv pip install -e . && python unzip_files.py
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - fromGroup: czsu-multi-agent-text-to-sql-env-group
    healthCheckPath: /docs
    autoDeploy: true
    plan: free