services:
  - type: web
    name: czsu-multi-agent-text-to-sql
    runtime: python
    buildCommand: python -m pip install -r requirements.txt && python unzip_files.py
    startCommand: python -m uvicorn api_server:app --host 0.0.0.0 --port $PORT --workers 1 --max-requests 100 --max-requests-jitter 10 --timeout-keep-alive 5 --limit-concurrency 200 --backlog 50
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - fromGroup: czsu-multi-agent-text-to-sql-env-group
    healthCheckPath: /docs
    autoDeploy: true
    plan: free